config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]

  match '/signup' , :to => 'users#new'
  match '/signin' , :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about'  , :to => 'pages#about'
  match '/help'   , :to => 'pages#help'

  root :to => "pages#home"

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content

  belongs_to :user
  
  validates :content, :presence => true, :length => { :maximum => 140 }
  validates :user_id, :presence => true
  
  default_scope :order => 'microposts.created_at DESC'
end

app/models/user.rb
# == Schema Information
# Schema version: 20120314102801
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#  admin              :boolean         default(FALSE)
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#

require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation

  has_many :microposts, :dependent => :destroy

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name , :presence   => true,
                    :length     => { :maximum => 50 }
  validates :email, :presence   => true,
                    :format     => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }

  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40 }

  before_save :encrypt_password

  def feed
    # preliminary, will be complete in Ch 12
    Micropost.where("user_id = ?", id)
  end
  
  # Return true if the user's password matches the submitted password.
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  private

    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_filter :authenticate, :only => [:create, :destroy]
  before_filter :authorized_user, :only => :destroy
  
  def create
    @micropost = current_user.microposts.build(params[:micropost])
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_path
    else
      @feed_items = []
      render 'pages/home'
    end
  end
  
  def destroy
    @micropost.destroy
    redirect_back_or root_path
  end
  
  private
  
    def authorized_user
      @micropost = current_user.microposts.find_by_id(params[:id])
      redirect_to root_path if @micropost.nil?
    end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
    if signed_in?
      @micropost = Micropost.new
      @feed_items = current_user.feed.paginate(:page => params[:page])
    end
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def help 
    @title = "Help"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end

  def create
    user = User.authenticate(params[:session][:email], 
                             params[:session][:password])

    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "Sign in"
      render :new
    else
      sign_in user
      # This was redirecting always to the user's profile page
      #   redirect_to user
      # Now, we redirect to whatever URI was requested before the sign-in, or the default user profile
      redirect_back_or user
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:index, :edit, :update]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user, :only => :destroy
  before_filter :deny_create, :only => [:new, :create]
  
  def new
    @user = User.new
    @title = "Sign up"
  end

  def index
    @title = "All users"
    #@users = User.all
    @users = User.paginate(:page => params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(:page => params[:page])
    @title = @user.name
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      @title="Sign up"
      render 'new'
    end
  end
  
  def edit
    @title = "Edit user"
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end
  
  def destroy
    user_to_destroy = User.find(params[:id])
    if ( user_to_destroy == current_user and current_user.admin? )
      flash[:error] = "Admin user: cannot destroy yourself!"
      redirect_to users_path
    else
      user_to_destroy.destroy
      flash[:success] = "User destroyed."
      redirect_to users_path
    end
  end
  
  private
  
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      if current_user.nil?
        redirect_to(signin_path)
      else
        redirect_to(root_path) unless current_user.admin?
      end
    end
    
    def deny_create
      if signed_in?
        redirect_to(root_path)
      end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper

  def logo
    image_tag("logo.png", :alt => "Sample App", :class => "round")
  end

  # Return a title on a per-page basis.
  def title
    base_title = "Ruby on Rails Tutorial Sample App"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user=user
  end

  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    # The un-optimized version of this would be:
    #   @current_user = user_from_remember_token
    # which would get executed on every page that the user visits
    
    # The optimized version is:

    @current_user ||= user_from_remember_token

    # which is equivalent to:
    # if @current_user.nil?
    #   @current_user = user_from_remember_token
    # else
    #   @current_user
    # end
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def authenticate
    deny_access unless signed_in?
  end
  
  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page"
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end
  

  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
    
    def store_location
      session[:return_to] = request.fullpath
    end
    
    def clear_return_to
      session[:return_to] = nil
    end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => h(user.name),
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
  <ul>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Contact", contact_path %></li>
    <li><a href="http://news.railstutorial.org/">News</a></li>
    <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <% if signed_in? %>
      	<li><%= link_to "Users"   , users_path %></li>
        <li><%= link_to "Profile" , current_user %></li>
		<li><%= link_to "Settings", edit_user_path(current_user) %>
        <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <% else%>
        <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]--> 
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print' , :media => 'print'  %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
	<%= javascript_include_tag :defaults %>
  </head>

  <body>
    <div class="container">

      <%= render 'layouts/header' %>

      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>

      <%= render 'layouts/footer' %>

      <%= debug(params)   if Rails.env.development? %>

    </div>
  </body>

</html>

app/views/microposts/_micropost.html.erb
<tr>
  <td class="micropost">
	<span class="content"><%= micropost.content %></span>
	<span class="timestamp">
	  Posted <%= time_ago_in_words(micropost.created_at) %> ago.
	</span>
  </td>

	<% if current_user?(micropost.user) %>
		<td>
			<%= link_to "delete", micropost, :method => :delete,
																			 :confirm => "Are you sure?",
																			 :title => micropost.content %>
    </td>
  <% end %>  											
</tr>

app/views/pages/about.html.erb
    <h1>About Us</h1>
    <p>
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      is a project to make a book and screencasts to teach web development
      with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
      is the sample application for the tutorial.
    </p>

app/views/pages/contact.html.erb
    <h1>Contact</h1>
    <p>
      Contact Ruby on Rails Tutorial about the sample app at the
      <a href="http://railstutorial.org/feedback">feedback page</a>.
    </p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
  Get help on Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/pages/home.html.erb
<% if signed_in? %>
	<table class="front" summary="For signed-in users">
		<tr>
			<td class="main">
				<h1 class="micropost">What's up?</h1>
				<%= render 'shared/micropost_form' %>
				<%= render 'shared/feed' %>
			</td>
			<td class="sidebar round">
				<%= render 'shared/user_info' %>
			</td>
		</tr>
	</table>
<% else %>
  <h1>Sample App</h1>

  <p>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </p>

  <%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">

    <h2><%= pluralize(object.errors.count, "error") %>
      prohibited this <%= object.class.to_s.underscore.humanize.downcase %> from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
	<table class="microposts" summary="User microposts">
		<%= render :partial => 'shared/feed_item', :collection => @feed_items %>
	</table>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
	<td class="gravatar">
		<%= link_to gravatar_for(feed_item.user), feed_item.user %>
	</td>
	<td class="micropost">
		<span class="user">
			<%= link_to feed_item.user.name, feed_item.user %>
		</span>
		<span class="content"><%= feed_item.content %></span>
		<span class="timestamp">
			Posted <%= time_ago_in_words(feed_item.created_at) %>ago.
		</span>
	</td>
	<% if current_user?(feed_item.user) %>
		<td>
			<%= link_to "delete", feed_item, :method => :delete,
																			 :confirm => "Are you sure?",
																			 :title => feed_item.content %>
    </td>
  <% end %>  											
</tr>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| -%>
  <%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
		<%= f.text_area :content %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/shared/_user_info.html.erb
<div class="user_info">
	<a href="<%= user_path(current_user) %>">
		<%= gravatar_for current_user, :size => 30 %><br />
		<span class"user_name">
			<%= current_user.name %>
		</span><br />
		<span class="microposts">
			<%= pluralize(current_user.microposts.count, "microposts") %>
		</span>
	</a>
</div>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>

<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation, "Confirmation" %><br />
  <%= f.password_field :password_confirmation %>
</div>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, :size => 30 %>
	<%= link_to user.name, user %>
	<%= user.admin? ? "(Admin)" : "(Regular)" %>
	<% if current_user.admin? %>
		<%= link_to "delete", user, :method => :delete, :confirm => "You sure?",
									:title => "Delete #{user.name}"%>
    <% end %>
</li>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render "fields", :f => f %>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<div>
	<%= gravatar_for @user %>
	<a href="http://gravatar.com/emails" target="_blank">change</a>
</div>

app/views/users/index.html.erb
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
  <%= render "fields", :f => f %>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>

      <% unless @user.microposts.empty? %>
        <table class="microposts" summary="User microposts">
	      	<%= render @microposts %>
	    	</table>
	    	<%= will_paginate @microposts %>
	  	<% end %>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong> <%= link_to user_path(@user), @user%><br />
      <strong>Microposts</strong> <%= @user.microposts.count %>
    </td>
  </tr>
</table>